


module.exports  = {

    ADD_USER_REGISTERATION : 'ADD_USER_REGISTERATION',
    LOGOUT_USER : 'LOGOUT_USER',
    LOGIN_USER : 'LOGIN_USER',
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    CHANGE_USER : 'CHANGE_USER',
    CHECK_AUTHORIZED : 'CHECK_AUTHORIZED',

    LOGIN_FAILURE : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',


    GET_ALL_ROLES_NODE:'ALL_ROLE_NODES',

    ROLE_PERMISSION_START:'ROLE_PERMISSION_START',
    ROLE_PERMISSION_SUCCESS:'ROLE_PERMISSION_SUCCESS',
    ROLE_PERMISSION_FAIL:'ROLE_PERMISSION_FAIL',


    ROLE_GET_USERS : 'ROLE_GET_USERS',
    ROLE_GET_ALL_ROLES : 'ROLE_GET_ALL_ROLES',
    ROLE_SAVE_ID : 'ROLE_SAVE_ID',

    ROLE_GET_CHECKED_NODES : 'ROLE_GET_CHECKED_NODES',
    ROLE_CLEAR_ALL_STATE : 'ROLE_CLEAR_ALL_STATE',
    ROLE_CLEAR_STATE : 'ROLE_CLEAR_STATE',

    ROLE_APPROVE_ROLE: 'ROLE_APPROVE_ROLE',

    ROLE_SAVE_ROLE_DATA_INTO_GRID: 'ROLE_SAVE_ROLE_DATA_INTO_GRID',


    USER_MANAGEMENT_GET_ALL_USERS: 'USER_MANAGEMENT_GET_ALL_USERS',
    USER_MANAGEMENT_CLEAR_ALL_STATE : 'USER_MANAGEMENT_CLEAR_ALL_STATE',
    USER_MANAGEMENT_PERMISSION_FAIL:'USER_MANAGEMENT_PERMISSION_FAIL',
    USER_MANAGEMENT_GET_ALL_ROLES : 'USER_MANAGEMENT_GET_ALL_ROLES',
    USER_MANAGEMENT_CLEAR_STATE : 'USER_MANAGEMENT_CLEAR_STATE',
    USER_MANAGEMENT_SAVE_ID : 'USER_MANAGEMENT_SAVE_ID',
    USER_MANAGEMENT_GET_CHECKED_NODES : 'USER_MANAGEMENT_GET_CHECKED_NODES',
    USER_MANAGEMENT_GET_ALL_ROLES : 'USER_MANAGEMENT_GET_ALL_ROLES',
    USER_MANAGEMENT_PERMISSION_START : 'USER_MANAGEMENT_PERMISSION_START',
    USER_MANAGEMENT_PERMISSION_SUCCESS : 'USER_MANAGEMENT_PERMISSION_SUCCESS',
    USER_MANAGEMENT_APPROVE_USER : 'USER_MANAGEMENT_APPROVE_USER'
    
}
